#!/bin/bash

letterhead=$(php -r 'require($argv[1]); print($my["letterhead"] ?? "default");' "$4")
letterhead_file=src/_letterheads/$letterhead.php.pdt

[ -f "$letterhead_file" ] || { echo "Cannot find the letterhead template: $letterhead_file" > /dev/stderr; exit 2; }

pandoc -s --template=$letterhead_file $3

mkdir -p $(dirname .cache/include/$1.html)
echo "$2: $letterhead_file" >> .cache/include/$1.html
