#!/bin/bash

layout_file=src/_layouts/$(php -r 'require($argv[1]); print($my["layout"] ?? "default");' "$4").php.pdt

[ -f "$layout_file" ] || { echo "Cannot find the layout template: $layout_file" > /dev/stderr; exit 2; }

pandoc -s --template=$layout_file $3

include_dir=$(dirname .cache/include/$1.html)
test -d "$include_dir" || mkdir -p $include_dir
echo "$2: $layout_file" >> .cache/include/$1.html
